Task 2
irinaNMN/tasks-repository pull request #1
Opened 2024-04-16 12:33 UTC by irinaNMN

![image](https://github.com/irinaNMN/tasks-repository/assets/164022141/efbaf08d-b7ea-4bb2-84d4-ca3fa5786077)

2024-04-17 11:18 UTC, ngoncearu requested changes

2024-04-17 11:18 UTC, ngoncearu commented on task_2.html
> +<h1>27 august 1991, Republica Moldova devine stat independent şi suveran</h1> <!--here is used h6 -->
ar trebui sa fie de la h1 spre h6 dupa importanta
``<h1>Simbolurile statului</h1> ...``

2024-04-18 06:21 UTC, irinaNMN commented on task_2.html
> +<h1>27 august 1991, Republica Moldova devine stat independent şi suveran</h1> <!--here is used h6 -->
Done

2024-04-26 12:41 UTC, ngoncearu approved these changes

2024-04-26 17:30 UTC, merged