Task 12 Ordered List with Icons
irinaNMN/tasks-repository pull request #11
Opened 2024-04-16 13:35 UTC by irinaNMN

![image](https://github.com/irinaNMN/tasks-repository/assets/164022141/55d9ca0b-9808-4c8a-8438-d8c62c08b8be)

2024-04-17 14:07 UTC, ngoncearu requested changes

2024-04-17 14:07 UTC, ngoncearu commented on ord_list_icons.html
> +        .emoji_list li ::before {
`li::before` fara spatiu

2024-04-18 07:12 UTC, irinaNMN commented on ord_list_icons.html
> +        .emoji_list li ::before {
Done!

2024-04-26 12:43 UTC, ngoncearu approved these changes

2024-04-28 11:17 UTC, merged